//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaticResource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StaticResource.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm sản phẩm.
        /// </summary>
        public static string Admin_AddNewProduct {
            get {
                return ResourceManager.GetString("Admin_AddNewProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xuất dữ liệu.
        /// </summary>
        public static string Admin_ExportData {
            get {
                return ResourceManager.GetString("Admin_ExportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhật ký hoạt động.
        /// </summary>
        public static string Admin_Home_History {
            get {
                return ResourceManager.GetString("Admin_Home_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tin tức.
        /// </summary>
        public static string Admin_Home_Panel_Blog {
            get {
                return ResourceManager.GetString("Admin_Home_Panel_Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khách hàng.
        /// </summary>
        public static string Admin_Home_Panel_Customer {
            get {
                return ResourceManager.GetString("Admin_Home_Panel_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn hàng.
        /// </summary>
        public static string Admin_Home_Panel_Order {
            get {
                return ResourceManager.GetString("Admin_Home_Panel_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm.
        /// </summary>
        public static string Admin_Home_Panel_Product {
            get {
                return ResourceManager.GetString("Admin_Home_Panel_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem thêm.
        /// </summary>
        public static string Admin_Home_Panel_ViewMore {
            get {
                return ResourceManager.GetString("Admin_Home_Panel_ViewMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thống kê truy cập.
        /// </summary>
        public static string Admin_Home_Statistic {
            get {
                return ResourceManager.GetString("Admin_Home_Statistic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo đơn hàng đầu tiên của bạn.
        /// </summary>
        public static string Admin_Order_Button {
            get {
                return ResourceManager.GetString("Admin_Order_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Các đơn hàng sắp tới của bạn sẽ hiển thị ở đây nhé.
        /// </summary>
        public static string Admin_Order_Sub_Title_None {
            get {
                return ResourceManager.GetString("Admin_Order_Sub_Title_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý đơn hàng.
        /// </summary>
        public static string Admin_Order_Title {
            get {
                return ResourceManager.GetString("Admin_Order_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website của bạn chưa có đơn hàng nào.
        /// </summary>
        public static string Admin_Order_Title_None {
            get {
                return ResourceManager.GetString("Admin_Order_Title_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý sản phẩm.
        /// </summary>
        public static string Admin_Product_Title {
            get {
                return ResourceManager.GetString("Admin_Product_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm.
        /// </summary>
        public static string Admin_Search_Button {
            get {
                return ResourceManager.GetString("Admin_Search_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập từ khóa tìm kiếm.
        /// </summary>
        public static string Admin_Search_Place {
            get {
                return ResourceManager.GetString("Admin_Search_Place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đóng.
        /// </summary>
        public static string Admin_TextButton_Close {
            get {
                return ResourceManager.GetString("Admin_TextButton_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem thêm hoạt động.
        /// </summary>
        public static string Admin_TextButton_ViewActivity {
            get {
                return ResourceManager.GetString("Admin_TextButton_ViewActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin chào.
        /// </summary>
        public static string Admin_Welcome {
            get {
                return ResourceManager.GetString("Admin_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiếng Anh.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý ảnh.
        /// </summary>
        public static string ManageImage {
            get {
                return ResourceManager.GetString("ManageImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên sản phẩm.
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản.
        /// </summary>
        public static string SideBar_Account {
            get {
                return ResourceManager.GetString("SideBar_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tin tức.
        /// </summary>
        public static string SideBar_Blog {
            get {
                return ResourceManager.GetString("SideBar_Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục tin tức.
        /// </summary>
        public static string SideBar_BlogCategory {
            get {
                return ResourceManager.GetString("SideBar_BlogCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khách hàng.
        /// </summary>
        public static string SideBar_Customer {
            get {
                return ResourceManager.GetString("SideBar_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khuyến mãi.
        /// </summary>
        public static string SideBar_Discount {
            get {
                return ResourceManager.GetString("SideBar_Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên miền.
        /// </summary>
        public static string SideBar_Domain {
            get {
                return ResourceManager.GetString("SideBar_Domain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phản hồi khách hàng.
        /// </summary>
        public static string SideBar_Feedback {
            get {
                return ResourceManager.GetString("SideBar_Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string SideBar_File {
            get {
                return ResourceManager.GetString("SideBar_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang chủ.
        /// </summary>
        public static string SideBar_Home {
            get {
                return ResourceManager.GetString("SideBar_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nội dung.
        /// </summary>
        public static string SideBar_Label_Content {
            get {
                return ResourceManager.GetString("SideBar_Label_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang chủ.
        /// </summary>
        public static string SideBar_Label_Home {
            get {
                return ResourceManager.GetString("SideBar_Label_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string SideBar_Menu {
            get {
                return ResourceManager.GetString("SideBar_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo.
        /// </summary>
        public static string SideBar_Notification {
            get {
                return ResourceManager.GetString("SideBar_Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn hàng.
        /// </summary>
        public static string SideBar_Order {
            get {
                return ResourceManager.GetString("SideBar_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang nội dung.
        /// </summary>
        public static string SideBar_Page {
            get {
                return ResourceManager.GetString("SideBar_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanh toán.
        /// </summary>
        public static string SideBar_Pay {
            get {
                return ResourceManager.GetString("SideBar_Pay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm.
        /// </summary>
        public static string SideBar_Product {
            get {
                return ResourceManager.GetString("SideBar_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục sản phẩm.
        /// </summary>
        public static string SideBar_ProductCategory {
            get {
                return ResourceManager.GetString("SideBar_ProductCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cấu hình.
        /// </summary>
        public static string SideBar_Setting {
            get {
                return ResourceManager.GetString("SideBar_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cấu hình chung.
        /// </summary>
        public static string SideBar_SettingGlobal {
            get {
                return ResourceManager.GetString("SideBar_SettingGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giao diện.
        /// </summary>
        public static string SideBar_Theme {
            get {
                return ResourceManager.GetString("SideBar_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cấu hình website.
        /// </summary>
        public static string SileBar_Label_Configuration {
            get {
                return ResourceManager.GetString("SileBar_Label_Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiếng Việt.
        /// </summary>
        public static string VietNamese {
            get {
                return ResourceManager.GetString("VietNamese", resourceCulture);
            }
        }
    }
}
